"use client";

import { useState } from "react";
import axios from "axios";
import ProteinViewer from "./ProteinViewer";

export default function Home() {
  const [file, setFile] = useState<File | null>(null);
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);

  const handleSearch = async () => {
    if (!file) {
      alert("Please upload a .pdb file of the target key.");
      return;
    }

    setLoading(true);
    setResult(null);

    const formData = new FormData();
    formData.append("file", file);
    // We pass a default property so the backend's Unit 6 Bloom Filter still operates flawlessly!
    formData.append("required_property", "HAS_SULPHUR"); 

    try {
      const response = await axios.post("http://localhost:8000/upload_search", formData, {
        headers: { "Content-Type": "multipart/form-data" },
      });
      setResult(response.data);
    } catch (error) {
      console.error("Error connecting to SPIRE Engine", error);
      setResult({ error: "Failed to connect to the backend engine." });
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadReport = () => {
    if (!result || !result.match_found) return;

    const reportContent = `
=========================================
SPIRE ENGINE - CLINICAL SEARCH REPORT
=========================================
Uploaded Query File : ${file?.name || "N/A"}

--- MATCH RESULTS ---
Protein ID Match    : ${result.protein_id}
Metric Distance     : ${result.metric_distance.toFixed(4)}
GNN Binding Affinity: ${(result.ai_score * 100).toFixed(2)}%

--- ALPHA MISSENSE ---
Warning Triggered   : ${result.alphamissense_warning ? "YES (Highly Conserved / Pathogenic)" : "NO"}

Generated by SPIRE Bioinformatics Engine v4.0
    `;

    const blob = new Blob([reportContent.trim()], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `SPIRE_Report_${result.protein_id}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <main className="min-h-screen bg-[#050505] text-white p-8 font-sans">
      {/* Header */}
      <header className="mb-8 border-b border-neutral-800 pb-4 text-center">
        <h1 className="text-4xl font-extrabold tracking-tight text-emerald-500">SPIRE</h1>
        <p className="text-neutral-400 mt-1 text-sm">Spatial Protein Indexing & Retrieval Engine</p>
      </header>

      {/* SPLIT SCREEN LAYOUT */}
      <div className="max-w-7xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 h-[80vh]">
        
        {/* LEFT PANEL: Inputs */}
        <div className="border-2 border-neutral-800 p-8 flex flex-col gap-8 bg-neutral-900/30 rounded-xl">
          
          <div className="border border-neutral-700 p-6 bg-black text-center rounded-lg shadow-inner mt-12 mb-12 flex flex-col justify-center items-center h-48">
            <p className="mb-6 font-mono text-sm text-neutral-400">Upload the 3D Model (.pdb) of the target key</p>
            <input 
              type="file" 
              accept=".pdb"
              onChange={(e) => setFile(e.target.files ? e.target.files[0] : null)}
              className="w-full max-w-xs text-sm text-neutral-400 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:font-semibold file:bg-emerald-900 file:text-emerald-300 hover:file:bg-emerald-800 cursor-pointer"
            />
          </div>

          <button 
            onClick={handleSearch}
            disabled={loading}
            className="mt-auto w-full border-2 border-emerald-600 hover:bg-emerald-600 text-white font-bold py-4 rounded-lg transition-all uppercase tracking-widest disabled:opacity-50"
          >
            {loading ? "Scanning Database..." : "Execute Search"}
          </button>
        </div>

        {/* RIGHT PANEL: Results */}
        <div className="border-2 border-neutral-800 p-8 flex flex-col gap-6 bg-neutral-900/30 overflow-y-auto rounded-xl">
          
          {!result ? (
            <div className="flex-grow border border-neutral-700 flex items-center justify-center text-neutral-500 p-6 bg-black text-center rounded-lg font-mono text-sm">
              3D model of the lock and the keyhole <br/>(Awaiting PDB Search...)
            </div>
          ) : (
            <>
              {/* 3D Model Viewer */}
              {result.match_found ? (
                 <div className="flex-grow border border-neutral-700 bg-black rounded-lg overflow-hidden min-h-[400px]">
                   <ProteinViewer proteinId={result.protein_id} />
                 </div>
              ) : (
                <div className="flex-grow border border-red-900/50 flex flex-col items-center justify-center text-red-400 p-6 bg-red-950/20 text-center rounded-lg">
                   <span className="text-2xl font-bold mb-2">Search Rejected</span>
                   <span>{result.reason || result.error}</span>
                </div>
              )}

              {/* Data Metrics */}
              {result.match_found && (
                <div className="flex gap-4 border border-neutral-700 p-4 bg-black rounded-lg">
                  <div className="w-1/2">
                    <p className="text-xs text-neutral-500 uppercase">Metric Distance</p>
                    <p className="text-lg font-mono text-emerald-400">{result.metric_distance.toFixed(4)}</p>
                  </div>
                  <div className="w-1/2">
                    <p className="text-xs text-neutral-500 uppercase">GNN Affinity</p>
                    <p className="text-lg font-mono text-blue-400">{(result.ai_score * 100).toFixed(2)}%</p>
                  </div>
                </div>
              )}

              {/* Pharmacology Context Panel */}
              {result.match_found && result.pharmacology && (
                <div className="border border-emerald-900/50 p-4 bg-emerald-950/10 rounded-lg text-sm">
                  <h3 className="font-bold text-emerald-500 mb-3 border-b border-emerald-900/50 pb-2">
                    CLINICAL PHARMACOLOGY PROFILE
                  </h3>
                  <div className="grid grid-cols-1 gap-2 text-neutral-300">
                    <p><span className="text-neutral-500 font-mono text-xs">TARGET: </span> <br/>{result.pharmacology.protein_name}</p>
                    <p><span className="text-neutral-500 font-mono text-xs">PRIMARY TISSUE: </span> <br/>{result.pharmacology.primary_tissue}</p>
                    <p><span className="text-neutral-500 font-mono text-xs">KNOWN LIGANDS (DRUGS): </span> <br/><span className="text-blue-400">{result.pharmacology.known_ligands}</span></p>
                    <p><span className="text-neutral-500 font-mono text-xs">CLINICAL APPLICATION: </span> <br/>{result.pharmacology.clinical_target}</p>
                    <p><span className="text-neutral-500 font-mono text-xs">ADVERSE EFFECTS: </span> <br/><span className="text-red-400">{result.pharmacology.side_effects}</span></p>
                  </div>
                </div>
              )}

              {/* AlphaMissense Warning */}
              {result.alphamissense_warning && (
                <div className="border-2 border-red-800 p-4 bg-red-950/40 text-red-200 rounded-lg">
                  <p className="font-bold text-red-400 mb-1">⚠️ AlphaMissense Critical Warning</p>
                  <p className="text-sm">DeepMind data indicates mutations in this region are likely pathogenic. Proceed with caution.</p>
                </div>
              )}

              {/* Downloadable Files */}
              {result.match_found && (
                <button 
                  onClick={handleDownloadReport}
                  className="w-full border border-neutral-700 hover:bg-neutral-800 p-4 text-center font-mono text-sm transition-colors bg-black cursor-pointer text-neutral-300 hover:text-white rounded-lg"
                >
                  Downloadable Files (.txt Report)
                </button>
              )}
            </>
          )}

        </div>
      </div>
    </main>
  );
}